### ISSUE TITLE
Don't compile with kernel 4.13

### ISSUE THREAD

**Issue by tolotos-rgu** [diederikdehaas/rtl8814AU#15]
```
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/4.13.0-32-generic/build M=/home/rgu/_test/rtl8814AU  modules
make[1]: Verzeichnis „/usr/src/linux-headers-4.13.0-32-generic“ wird betreten
  CC [M]  /home/rgu/_test/rtl8814AU/core/rtw_cmd.o
In file included from /home/rgu/_test/rtl8814AU/include/drv_types.h:32:0,
                 from /home/rgu/_test/rtl8814AU/core/rtw_cmd.c:22:
/home/rgu/_test/rtl8814AU/include/osdep_service.h: In function ‘thread_enter’:
/home/rgu/_test/rtl8814AU/include/osdep_service.h:343:2: error: implicit declaration of function ‘allow_signal’; did you mean ‘do_signal’? [-Werror=implicit-function-declaration]
  allow_signal(SIGTERM);
  ^~~~~~~~~~~~
  do_signal
/home/rgu/_test/rtl8814AU/include/osdep_service.h: In function ‘flush_signals_thread’:
/home/rgu/_test/rtl8814AU/include/osdep_service.h:353:6: error: implicit declaration of function ‘signal_pending’; did you mean ‘timer_pending’? [-Werror=implicit-function-declaration]
  if (signal_pending (current))
      ^~~~~~~~~~~~~~
      timer_pending
/home/rgu/_test/rtl8814AU/include/osdep_service.h:355:3: error: implicit declaration of function ‘flush_signals’; did you mean ‘do_signal’? [-Werror=implicit-function-declaration]
   flush_signals(current);
   ^~~~~~~~~~~~~
   do_signal
cc1: some warnings being treated as errors
scripts/Makefile.build:308: die Regel für Ziel „/home/rgu/_test/rtl8814AU/core/rtw_cmd.o“ scheiterte
make[2]: *** [/home/rgu/_test/rtl8814AU/core/rtw_cmd.o] Fehler 1
Makefile:1550: die Regel für Ziel „_module_/home/rgu/_test/rtl8814AU“ scheiterte
make[1]: *** [_module_/home/rgu/_test/rtl8814AU] Fehler 2
make[1]: Verzeichnis „/usr/src/linux-headers-4.13.0-32-generic“ wird verlassen
Makefile:1699: die Regel für Ziel „modules“ scheiterte
make: *** [modules] Fehler 2
```

**Comment by DXCanas** [comment]
Getting the same issue here

**Comment by diederikdehaas** [comment]
Running `make KVER=4.13.0-1-amd64` against the updated driver version work here (on Debian).
(IIRC prepending your command with `LANG=C` would output things in English)
